name: Create Release

on:
  push:
    branches:
      - main
permissions:
  contents: write
  
jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Get the last commit message
      id: last_commit
      run: echo "::set-output name=message::$(git log -1 --pretty=%B)"

    - name: Determine version bump
      id: version_bump
      run: |
        if [[ "${{ steps.last_commit.outputs.message }}" == *"major-rel"* ]]; then
          echo "::set-output name=level::major"
        else
          echo "::set-output name=level::minor"
        fi

    - name: Get the current version
      id: current_version
      run: |
        if [ -f VERSION ]; then
          echo "::set-output name=version::$(cat VERSION)"
        else
          echo "::set-output name=version::0.0.0"
        fi

    - name: Calculate new version
      id: new_version
      run: |
        current_version=${{ steps.current_version.outputs.version }}
        level=${{ steps.version_bump.outputs.level }}
        IFS='.' read -r -a version_parts <<< "$current_version"
        if [ "$level" == "major" ]; then
          new_version="$((version_parts[0] + 1)).0.0"
        else
          new_version="${version_parts[0]}.$((version_parts[1] + 1)).0"
        fi
        echo "New version: $new_version"
        echo "$new_version" > VERSION
        echo "::set-output name=version::$new_version"

    - name: Commit new version
      run: |
        git config --global user.name "release-builder"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add VERSION
        git commit -m "Release version ${{ steps.new_version.outputs.version }}"
        git push origin main

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.new_version.outputs.version }}
        release_name: Release ${{ steps.new_version.outputs.version }}
        body: |
          This is the ${{ steps.version_bump.outputs.level }} release.
        draft: false
        prerelease: false
